/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using SF.Snowball;

namespace SF.Snowball.Ext
{
	/// <summary>
	/// This class was automatically generated by a Snowball to Java compiler
	/// It implements the stemming algorithm defined by a snowball script.
	/// </summary>
	/// <remarks>
	/// This class was automatically generated by a Snowball to Java compiler
	/// It implements the stemming algorithm defined by a snowball script.
	/// </remarks>
	public class ArmenianStemmer : SnowballProgram
	{
		private const long serialVersionUID = 1L;

		private static readonly ArmenianStemmer methodObject = new ArmenianStemmer();

		private static readonly Among[] a_0 =
		{ new Among("\u0580\u0578\u0580\u0564"
		    , -1, 1, string.Empty, methodObject), new Among("\u0565\u0580\u0578\u0580\u0564"
		        , 0, 1, string.Empty, methodObject), new Among("\u0561\u056C\u056B", -1, 1, string.Empty
		            , methodObject), new Among("\u0561\u056F\u056B", -1, 1, string.Empty, methodObject
		                ), new Among("\u0578\u0580\u0561\u056F", -1, 1, string.Empty, methodObject), new 
		                    Among("\u0565\u0572", -1, 1, string.Empty, methodObject), new Among("\u0561\u056F\u0561\u0576"
		                        , -1, 1, string.Empty, methodObject), new Among("\u0561\u0580\u0561\u0576", -1, 
		                            1, string.Empty, methodObject), new Among("\u0565\u0576", -1, 1, string.Empty, methodObject
		                                ), new Among("\u0565\u056F\u0565\u0576", 8, 1, string.Empty, methodObject), new 
		                                    Among("\u0565\u0580\u0565\u0576", 8, 1, string.Empty, methodObject), new Among("\u0578\u0580\u0567\u0576"
		                                        , -1, 1, string.Empty, methodObject), new Among("\u056B\u0576", -1, 1, string.Empty
		                                            , methodObject), new Among("\u0563\u056B\u0576", 12, 1, string.Empty, methodObject
		                                                ), new Among("\u0578\u057E\u056B\u0576", 12, 1, string.Empty, methodObject), new 
		                                                    Among("\u056C\u0561\u0575\u0576", -1, 1, string.Empty, methodObject), new Among(
		                                                        "\u057E\u0578\u0582\u0576", -1, 1, string.Empty, methodObject), new Among("\u057A\u0565\u057D"
		                                                            , -1, 1, string.Empty, methodObject), new Among("\u056B\u057E", -1, 1, string.Empty
		                                                                , methodObject), new Among("\u0561\u057F", -1, 1, string.Empty, methodObject), new 
		                                                                    Among("\u0561\u057E\u0565\u057F", -1, 1, string.Empty, methodObject), new Among(
		                                                                        "\u056F\u0578\u057F", -1, 1, string.Empty, methodObject), new Among("\u0562\u0561\u0580"
		                                                                            , -1, 1, string.Empty, methodObject) };

		private static readonly Among[] a_1 =
		{ new Among("\u0561", -1, 1, string.Empty
		    , methodObject), new Among("\u0561\u0581\u0561", 0, 1, string.Empty, methodObject
		        ), new Among("\u0565\u0581\u0561", 0, 1, string.Empty, methodObject), new Among(
		            "\u057E\u0565", -1, 1, string.Empty, methodObject), new Among("\u0561\u0581\u0580\u056B"
		                , -1, 1, string.Empty, methodObject), new Among("\u0561\u0581\u056B", -1, 1, string.Empty
		                    , methodObject), new Among("\u0565\u0581\u056B", -1, 1, string.Empty, methodObject
		                        ), new Among("\u057E\u0565\u0581\u056B", 6, 1, string.Empty, methodObject), new 
		                            Among("\u0561\u056C", -1, 1, string.Empty, methodObject), new Among("\u0568\u0561\u056C"
		                                , 8, 1, string.Empty, methodObject), new Among("\u0561\u0576\u0561\u056C", 8, 1, 
		                                    string.Empty, methodObject), new Among("\u0565\u0576\u0561\u056C", 8, 1, string.Empty
		                                        , methodObject), new Among("\u0561\u0581\u0576\u0561\u056C", 8, 1, string.Empty, 
		                                            methodObject), new Among("\u0565\u056C", -1, 1, string.Empty, methodObject), new 
		                                                Among("\u0568\u0565\u056C", 13, 1, string.Empty, methodObject), new Among("\u0576\u0565\u056C"
		                                                    , 13, 1, string.Empty, methodObject), new Among("\u0581\u0576\u0565\u056C", 15, 
		                                                        1, string.Empty, methodObject), new Among("\u0565\u0581\u0576\u0565\u056C", 16, 
		                                                            1, string.Empty, methodObject), new Among("\u0579\u0565\u056C", 13, 1, string.Empty
		                                                                , methodObject), new Among("\u057E\u0565\u056C", 13, 1, string.Empty, methodObject
		                                                                    ), new Among("\u0561\u0581\u057E\u0565\u056C", 19, 1, string.Empty, methodObject
		                                                                        ), new Among("\u0565\u0581\u057E\u0565\u056C", 19, 1, string.Empty, methodObject
		                                                                            ), new Among("\u057F\u0565\u056C", 13, 1, string.Empty, methodObject), new Among
		                                                                                ("\u0561\u057F\u0565\u056C", 22, 1, string.Empty, methodObject), new Among("\u0578\u057F\u0565\u056C"
		                                                                                    , 22, 1, string.Empty, methodObject), new Among("\u056F\u0578\u057F\u0565\u056C"
		                                                                                        , 24, 1, string.Empty, methodObject), new Among("\u057E\u0561\u056E", -1, 1, string.Empty
		                                                                                            , methodObject), new Among("\u0578\u0582\u0574", -1, 1, string.Empty, methodObject
		                                                                                                ), new Among("\u057E\u0578\u0582\u0574", 27, 1, string.Empty, methodObject), new 
		                                                                                                    Among("\u0561\u0576", -1, 1, string.Empty, methodObject), new Among("\u0581\u0561\u0576"
		                                                                                                        , 29, 1, string.Empty, methodObject), new Among("\u0561\u0581\u0561\u0576", 30, 
		                                                                                                            1, string.Empty, methodObject), new Among("\u0561\u0581\u0580\u056B\u0576", -1, 
		                                                                                                                1, string.Empty, methodObject), new Among("\u0561\u0581\u056B\u0576", -1, 1, string.Empty
		                                                                                                                    , methodObject), new Among("\u0565\u0581\u056B\u0576", -1, 1, string.Empty, methodObject
		                                                                                                                        ), new Among("\u057E\u0565\u0581\u056B\u0576", 34, 1, string.Empty, methodObject
		                                                                                                                            ), new Among("\u0561\u056C\u056B\u057D", -1, 1, string.Empty, methodObject), new 
		                                                                                                                                Among("\u0565\u056C\u056B\u057D", -1, 1, string.Empty, methodObject), new Among(
		                                                                                                                                    "\u0561\u057E", -1, 1, string.Empty, methodObject), new Among("\u0561\u0581\u0561\u057E"
		                                                                                                                                        , 38, 1, string.Empty, methodObject), new Among("\u0565\u0581\u0561\u057E", 38, 
		                                                                                                                                            1, string.Empty, methodObject), new Among("\u0561\u056C\u0578\u057E", -1, 1, string.Empty
		                                                                                                                                                , methodObject), new Among("\u0565\u056C\u0578\u057E", -1, 1, string.Empty, methodObject
		                                                                                                                                                    ), new Among("\u0561\u0580", -1, 1, string.Empty, methodObject), new Among("\u0561\u0581\u0561\u0580"
		                                                                                                                                                        , 43, 1, string.Empty, methodObject), new Among("\u0565\u0581\u0561\u0580", 43, 
		                                                                                                                                                            1, string.Empty, methodObject), new Among("\u0561\u0581\u0580\u056B\u0580", -1, 
		                                                                                                                                                                1, string.Empty, methodObject), new Among("\u0561\u0581\u056B\u0580", -1, 1, string.Empty
		                                                                                                                                                                    , methodObject), new Among("\u0565\u0581\u056B\u0580", -1, 1, string.Empty, methodObject
		                                                                                                                                                                        ), new Among("\u057E\u0565\u0581\u056B\u0580", 48, 1, string.Empty, methodObject
		                                                                                                                                                                            ), new Among("\u0561\u0581", -1, 1, string.Empty, methodObject), new Among("\u0565\u0581"
		                                                                                                                                                                                , -1, 1, string.Empty, methodObject), new Among("\u0561\u0581\u0580\u0565\u0581"
		                                                                                                                                                                                    , 51, 1, string.Empty, methodObject), new Among("\u0561\u056C\u0578\u0582\u0581"
		                                                                                                                                                                                        , -1, 1, string.Empty, methodObject), new Among("\u0565\u056C\u0578\u0582\u0581"
		                                                                                                                                                                                            , -1, 1, string.Empty, methodObject), new Among("\u0561\u056C\u0578\u0582", -1, 
		                                                                                                                                                                                                1, string.Empty, methodObject), new Among("\u0565\u056C\u0578\u0582", -1, 1, string.Empty
		                                                                                                                                                                                                    , methodObject), new Among("\u0561\u0584", -1, 1, string.Empty, methodObject), new 
		                                                                                                                                                                                                        Among("\u0581\u0561\u0584", 57, 1, string.Empty, methodObject), new Among("\u0561\u0581\u0561\u0584"
		                                                                                                                                                                                                            , 58, 1, string.Empty, methodObject), new Among("\u0561\u0581\u0580\u056B\u0584"
		                                                                                                                                                                                                                , -1, 1, string.Empty, methodObject), new Among("\u0561\u0581\u056B\u0584", -1, 
		                                                                                                                                                                                                                    1, string.Empty, methodObject), new Among("\u0565\u0581\u056B\u0584", -1, 1, string.Empty
		                                                                                                                                                                                                                        , methodObject), new Among("\u057E\u0565\u0581\u056B\u0584", 62, 1, string.Empty
		                                                                                                                                                                                                                            , methodObject), new Among("\u0561\u0576\u0584", -1, 1, string.Empty, methodObject
		                                                                                                                                                                                                                                ), new Among("\u0581\u0561\u0576\u0584", 64, 1, string.Empty, methodObject), new 
		                                                                                                                                                                                                                                    Among("\u0561\u0581\u0561\u0576\u0584", 65, 1, string.Empty, methodObject), new 
		                                                                                                                                                                                                                                        Among("\u0561\u0581\u0580\u056B\u0576\u0584", -1, 1, string.Empty, methodObject)
		    , new Among("\u0561\u0581\u056B\u0576\u0584", -1, 1, string.Empty, methodObject)
		    , new Among("\u0565\u0581\u056B\u0576\u0584", -1, 1, string.Empty, methodObject)
		    , new Among("\u057E\u0565\u0581\u056B\u0576\u0584", 69, 1, string.Empty, methodObject
		        ) };

		private static readonly Among[] a_2 =
		{ new Among("\u0578\u0580\u0564", 
		    -1, 1, string.Empty, methodObject), new Among("\u0578\u0582\u0575\u0569", -1, 1, 
		        string.Empty, methodObject), new Among("\u0578\u0582\u0570\u056B", -1, 1, string.Empty
		            , methodObject), new Among("\u0581\u056B", -1, 1, string.Empty, methodObject), new 
		                Among("\u056B\u056C", -1, 1, string.Empty, methodObject), new Among("\u0561\u056F"
		                    , -1, 1, string.Empty, methodObject), new Among("\u0575\u0561\u056F", 5, 1, string.Empty
		                        , methodObject), new Among("\u0561\u0576\u0561\u056F", 5, 1, string.Empty, methodObject
		                            ), new Among("\u056B\u056F", -1, 1, string.Empty, methodObject), new Among("\u0578\u0582\u056F"
		                                , -1, 1, string.Empty, methodObject), new Among("\u0561\u0576", -1, 1, string.Empty
		                                    , methodObject), new Among("\u057A\u0561\u0576", 10, 1, string.Empty, methodObject
		                                        ), new Among("\u057D\u057F\u0561\u0576", 10, 1, string.Empty, methodObject), new 
		                                            Among("\u0561\u0580\u0561\u0576", 10, 1, string.Empty, methodObject), new Among(
		                                                "\u0565\u0572\u0567\u0576", -1, 1, string.Empty, methodObject), new Among("\u0575\u0578\u0582\u0576"
		                                                    , -1, 1, string.Empty, methodObject), new Among("\u0578\u0582\u0569\u0575\u0578\u0582\u0576"
		                                                        , 15, 1, string.Empty, methodObject), new Among("\u0561\u056E\u0578", -1, 1, string.Empty
		                                                            , methodObject), new Among("\u056B\u0579", -1, 1, string.Empty, methodObject), new 
		                                                                Among("\u0578\u0582\u057D", -1, 1, string.Empty, methodObject), new Among("\u0578\u0582\u057D\u057F"
		                                                                    , -1, 1, string.Empty, methodObject), new Among("\u0563\u0561\u0580", -1, 1, string.Empty
		                                                                        , methodObject), new Among("\u057E\u0578\u0580", -1, 1, string.Empty, methodObject
		                                                                            ), new Among("\u0561\u057E\u0578\u0580", 22, 1, string.Empty, methodObject), new 
		                                                                                Among("\u0578\u0581", -1, 1, string.Empty, methodObject), new Among("\u0561\u0576\u0585\u0581"
		                                                                                    , -1, 1, string.Empty, methodObject), new Among("\u0578\u0582", -1, 1, string.Empty
		                                                                                        , methodObject), new Among("\u0584", -1, 1, string.Empty, methodObject), new Among
		                                                                                            ("\u0579\u0565\u0584", 27, 1, string.Empty, methodObject), new Among("\u056B\u0584"
		                                                                                                , 27, 1, string.Empty, methodObject), new Among("\u0561\u056C\u056B\u0584", 29, 
		                                                                                                    1, string.Empty, methodObject), new Among("\u0561\u0576\u056B\u0584", 29, 1, string.Empty
		                                                                                                        , methodObject), new Among("\u057E\u0561\u056E\u0584", 27, 1, string.Empty, methodObject
		                                                                                                            ), new Among("\u0578\u0582\u0575\u0584", 27, 1, string.Empty, methodObject), new 
		                                                                                                                Among("\u0565\u0576\u0584", 27, 1, string.Empty, methodObject), new Among("\u0578\u0576\u0584"
		                                                                                                                    , 27, 1, string.Empty, methodObject), new Among("\u0578\u0582\u0576\u0584", 27, 
		                                                                                                                        1, string.Empty, methodObject), new Among("\u0574\u0578\u0582\u0576\u0584", 36, 
		                                                                                                                            1, string.Empty, methodObject), new Among("\u056B\u0579\u0584", 27, 1, string.Empty
		                                                                                                                                , methodObject), new Among("\u0561\u0580\u0584", 27, 1, string.Empty, methodObject
		                                                                                                                                    ) };

		private static readonly Among[] a_3 =
		{ new Among("\u057D\u0561", -1, 1
		    , string.Empty, methodObject), new Among("\u057E\u0561", -1, 1, string.Empty, methodObject
		        ), new Among("\u0561\u0574\u0562", -1, 1, string.Empty, methodObject), new Among
		            ("\u0564", -1, 1, string.Empty, methodObject), new Among("\u0561\u0576\u0564", 3
		                , 1, string.Empty, methodObject), new Among("\u0578\u0582\u0569\u0575\u0561\u0576\u0564"
		                    , 4, 1, string.Empty, methodObject), new Among("\u057E\u0561\u0576\u0564", 4, 1, 
		                        string.Empty, methodObject), new Among("\u0578\u057B\u0564", 3, 1, string.Empty, 
		                            methodObject), new Among("\u0565\u0580\u0564", 3, 1, string.Empty, methodObject)
		    , new Among("\u0576\u0565\u0580\u0564", 8, 1, string.Empty, methodObject), new Among
		        ("\u0578\u0582\u0564", 3, 1, string.Empty, methodObject), new Among("\u0568", -1
		            , 1, string.Empty, methodObject), new Among("\u0561\u0576\u0568", 11, 1, string.Empty
		                , methodObject), new Among("\u0578\u0582\u0569\u0575\u0561\u0576\u0568", 12, 1, 
		                    string.Empty, methodObject), new Among("\u057E\u0561\u0576\u0568", 12, 1, string.Empty
		                        , methodObject), new Among("\u0578\u057B\u0568", 11, 1, string.Empty, methodObject
		                            ), new Among("\u0565\u0580\u0568", 11, 1, string.Empty, methodObject), new Among
		                                ("\u0576\u0565\u0580\u0568", 16, 1, string.Empty, methodObject), new Among("\u056B"
		                                    , -1, 1, string.Empty, methodObject), new Among("\u057E\u056B", 18, 1, string.Empty
		                                        , methodObject), new Among("\u0565\u0580\u056B", 18, 1, string.Empty, methodObject
		                                            ), new Among("\u0576\u0565\u0580\u056B", 20, 1, string.Empty, methodObject), new 
		                                                Among("\u0561\u0576\u0578\u0582\u0574", -1, 1, string.Empty, methodObject), new 
		                                                    Among("\u0565\u0580\u0578\u0582\u0574", -1, 1, string.Empty, methodObject), new 
		                                                        Among("\u0576\u0565\u0580\u0578\u0582\u0574", 23, 1, string.Empty, methodObject)
		    , new Among("\u0576", -1, 1, string.Empty, methodObject), new Among("\u0561\u0576"
		        , 25, 1, string.Empty, methodObject), new Among("\u0578\u0582\u0569\u0575\u0561\u0576"
		            , 26, 1, string.Empty, methodObject), new Among("\u057E\u0561\u0576", 26, 1, string.Empty
		                , methodObject), new Among("\u056B\u0576", 25, 1, string.Empty, methodObject), new 
		                    Among("\u0565\u0580\u056B\u0576", 29, 1, string.Empty, methodObject), new Among(
		                        "\u0576\u0565\u0580\u056B\u0576", 30, 1, string.Empty, methodObject), new Among(
		                            "\u0578\u0582\u0569\u0575\u0561\u0576\u0576", 25, 1, string.Empty, methodObject)
		    , new Among("\u0565\u0580\u0576", 25, 1, string.Empty, methodObject), new Among(
		        "\u0576\u0565\u0580\u0576", 33, 1, string.Empty, methodObject), new Among("\u0578\u0582\u0576"
		            , 25, 1, string.Empty, methodObject), new Among("\u0578\u057B", -1, 1, string.Empty
		                , methodObject), new Among("\u0578\u0582\u0569\u0575\u0561\u0576\u057D", -1, 1, 
		                    string.Empty, methodObject), new Among("\u057E\u0561\u0576\u057D", -1, 1, string.Empty
		                        , methodObject), new Among("\u0578\u057B\u057D", -1, 1, string.Empty, methodObject
		                            ), new Among("\u0578\u057E", -1, 1, string.Empty, methodObject), new Among("\u0561\u0576\u0578\u057E"
		                                , 40, 1, string.Empty, methodObject), new Among("\u057E\u0578\u057E", 40, 1, string.Empty
		                                    , methodObject), new Among("\u0565\u0580\u0578\u057E", 40, 1, string.Empty, methodObject
		                                        ), new Among("\u0576\u0565\u0580\u0578\u057E", 43, 1, string.Empty, methodObject
		                                            ), new Among("\u0565\u0580", -1, 1, string.Empty, methodObject), new Among("\u0576\u0565\u0580"
		                                                , 45, 1, string.Empty, methodObject), new Among("\u0581", -1, 1, string.Empty, methodObject
		                                                    ), new Among("\u056B\u0581", 47, 1, string.Empty, methodObject), new Among("\u057E\u0561\u0576\u056B\u0581"
		                                                        , 48, 1, string.Empty, methodObject), new Among("\u0578\u057B\u056B\u0581", 48, 
		                                                            1, string.Empty, methodObject), new Among("\u057E\u056B\u0581", 48, 1, string.Empty
		                                                                , methodObject), new Among("\u0565\u0580\u056B\u0581", 48, 1, string.Empty, methodObject
		                                                                    ), new Among("\u0576\u0565\u0580\u056B\u0581", 52, 1, string.Empty, methodObject
		                                                                        ), new Among("\u0581\u056B\u0581", 48, 1, string.Empty, methodObject), new Among
		                                                                            ("\u0578\u0581", 47, 1, string.Empty, methodObject), new Among("\u0578\u0582\u0581"
		                                                                                , 47, 1, string.Empty, methodObject) };

		private static readonly int[] g_v = { 209, 4, 128, 0, 18 };

		private int I_p2;

		private int I_pV;

		// This file was generated automatically by the Snowball to Java compiler
		private void Copy_from(ArmenianStemmer other)
		{
			I_p2 = other.I_p2;
			I_pV = other.I_pV;
			base.copy_from(other);
		}

		private bool R_mark_regions()
		{
			int v_1;
			// (, line 58
			I_pV = limit;
			I_p2 = limit;
			// do, line 62
			v_1 = cursor;
			do
			{
				// (, line 62
				// gopast, line 63
				while (true)
				{
					do
					{
						if (!(in_grouping(g_v, 1377, 1413)))
						{
							goto lab2_break;
						}
						goto golab1_break;
lab2_continue: ;
					}
					while (false);
lab2_break: ;
					if (cursor >= limit)
					{
						goto lab0_break;
					}
					cursor++;
golab1_continue: ;
				}
golab1_break: ;
				// setmark pV, line 63
				I_pV = cursor;
				// gopast, line 63
				while (true)
				{
					do
					{
						if (!(out_grouping(g_v, 1377, 1413)))
						{
							goto lab4_break;
						}
						goto golab3_break;
lab4_continue: ;
					}
					while (false);
lab4_break: ;
					if (cursor >= limit)
					{
						goto lab0_break;
					}
					cursor++;
golab3_continue: ;
				}
golab3_break: ;
				// gopast, line 64
				while (true)
				{
					do
					{
						if (!(in_grouping(g_v, 1377, 1413)))
						{
							goto lab6_break;
						}
						goto golab5_break;
lab6_continue: ;
					}
					while (false);
lab6_break: ;
					if (cursor >= limit)
					{
						goto lab0_break;
					}
					cursor++;
golab5_continue: ;
				}
golab5_break: ;
				// gopast, line 64
				while (true)
				{
					do
					{
						if (!(out_grouping(g_v, 1377, 1413)))
						{
							goto lab8_break;
						}
						goto golab7_break;
lab8_continue: ;
					}
					while (false);
lab8_break: ;
					if (cursor >= limit)
					{
						goto lab0_break;
					}
					cursor++;
golab7_continue: ;
				}
golab7_break: ;
				// setmark p2, line 64
				I_p2 = cursor;
lab0_continue: ;
			}
			while (false);
lab0_break: ;
			cursor = v_1;
			return true;
		}

		private bool R_R2()
		{
			if (!(I_p2 <= cursor))
			{
				return false;
			}
			return true;
		}

		private bool R_adjective()
		{
			int among_var;
			// (, line 72
			// [, line 73
			ket = cursor;
			// substring, line 73
			among_var = find_among_b(a_0, 23);
			if (among_var == 0)
			{
				return false;
			}
			// ], line 73
			bra = cursor;
			switch (among_var)
			{
				case 0:
				{
					return false;
				}

				case 1:
				{
					// (, line 98
					// delete, line 98
					slice_del();
					break;
				}
			}
			return true;
		}

		private bool R_verb()
		{
			int among_var;
			// (, line 102
			// [, line 103
			ket = cursor;
			// substring, line 103
			among_var = find_among_b(a_1, 71);
			if (among_var == 0)
			{
				return false;
			}
			// ], line 103
			bra = cursor;
			switch (among_var)
			{
				case 0:
				{
					return false;
				}

				case 1:
				{
					// (, line 176
					// delete, line 176
					slice_del();
					break;
				}
			}
			return true;
		}

		private bool R_noun()
		{
			int among_var;
			// (, line 180
			// [, line 181
			ket = cursor;
			// substring, line 181
			among_var = find_among_b(a_2, 40);
			if (among_var == 0)
			{
				return false;
			}
			// ], line 181
			bra = cursor;
			switch (among_var)
			{
				case 0:
				{
					return false;
				}

				case 1:
				{
					// (, line 223
					// delete, line 223
					slice_del();
					break;
				}
			}
			return true;
		}

		private bool R_ending()
		{
			int among_var;
			// (, line 227
			// [, line 228
			ket = cursor;
			// substring, line 228
			among_var = find_among_b(a_3, 57);
			if (among_var == 0)
			{
				return false;
			}
			// ], line 228
			bra = cursor;
			// call R2, line 228
			if (!R_R2())
			{
				return false;
			}
			switch (among_var)
			{
				case 0:
				{
					return false;
				}

				case 1:
				{
					// (, line 287
					// delete, line 287
					slice_del();
					break;
				}
			}
			return true;
		}

		public override bool Stem()
		{
			int v_1;
			int v_2;
			int v_3;
			int v_4;
			int v_5;
			int v_6;
			int v_7;
			// (, line 292
			// do, line 294
			v_1 = cursor;
			do
			{
				// call mark_regions, line 294
				if (!R_mark_regions())
				{
					goto lab0_break;
				}
lab0_continue: ;
			}
			while (false);
lab0_break: ;
			cursor = v_1;
			// backwards, line 295
			limit_backward = cursor;
			cursor = limit;
			// setlimit, line 295
			v_2 = limit - cursor;
			// tomark, line 295
			if (cursor < I_pV)
			{
				return false;
			}
			cursor = I_pV;
			v_3 = limit_backward;
			limit_backward = cursor;
			cursor = limit - v_2;
			// (, line 295
			// do, line 296
			v_4 = limit - cursor;
			do
			{
				// call ending, line 296
				if (!R_ending())
				{
					goto lab1_break;
				}
lab1_continue: ;
			}
			while (false);
lab1_break: ;
			cursor = limit - v_4;
			// do, line 297
			v_5 = limit - cursor;
			do
			{
				// call verb, line 297
				if (!R_verb())
				{
					goto lab2_break;
				}
lab2_continue: ;
			}
			while (false);
lab2_break: ;
			cursor = limit - v_5;
			// do, line 298
			v_6 = limit - cursor;
			do
			{
				// call adjective, line 298
				if (!R_adjective())
				{
					goto lab3_break;
				}
lab3_continue: ;
			}
			while (false);
lab3_break: ;
			cursor = limit - v_6;
			// do, line 299
			v_7 = limit - cursor;
			do
			{
				// call noun, line 299
				if (!R_noun())
				{
					goto lab4_break;
				}
lab4_continue: ;
			}
			while (false);
lab4_break: ;
			cursor = limit - v_7;
			limit_backward = v_3;
			cursor = limit_backward;
			return true;
		}

		public override bool Equals(object o)
		{
			return o is ArmenianStemmer;
		}

		public override int GetHashCode()
		{
			return typeof(ArmenianStemmer).FullName.GetHashCode();
		}
	}
}
