/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace SF.Snowball.Ext
{
	/// <summary>
	/// This class was automatically generated by a Snowball to Java compiler
	/// It implements the stemming algorithm defined by a snowball script.
	/// </summary>
	/// <remarks>
	/// This class was automatically generated by a Snowball to Java compiler
	/// It implements the stemming algorithm defined by a snowball script.
	/// </remarks>
	public class BasqueStemmer : SnowballProgram
	{
		private const long serialVersionUID = 1L;

		private static readonly BasqueStemmer methodObject = new BasqueStemmer();

		private static readonly Among[] a_0 =
		{ new Among("idea", -1, 1, string.Empty
		    , methodObject), new Among("bidea", 0, 1, string.Empty, methodObject), new Among
		        ("kidea", 0, 1, string.Empty, methodObject), new Among("pidea", 0, 1, string.Empty
		            , methodObject), new Among("kundea", -1, 1, string.Empty, methodObject), new Among
		                ("galea", -1, 1, string.Empty, methodObject), new Among("tailea", -1, 1, string.Empty
		                    , methodObject), new Among("tzailea", -1, 1, string.Empty, methodObject), new Among
		                        ("gunea", -1, 1, string.Empty, methodObject), new Among("kunea", -1, 1, string.Empty
		                            , methodObject), new Among("tzaga", -1, 1, string.Empty, methodObject), new Among
		                                ("gaia", -1, 1, string.Empty, methodObject), new Among("aldia", -1, 1, string.Empty
		                                    , methodObject), new Among("taldia", 12, 1, string.Empty, methodObject), new Among
		                                        ("karia", -1, 1, string.Empty, methodObject), new Among("garria", -1, 2, string.Empty
		                                            , methodObject), new Among("karria", -1, 1, string.Empty, methodObject), new Among
		                                                ("ka", -1, 1, string.Empty, methodObject), new Among("tzaka", 17, 1, string.Empty
		                                                    , methodObject), new Among("la", -1, 1, string.Empty, methodObject), new Among("mena"
		                                                        , -1, 1, string.Empty, methodObject), new Among("pena", -1, 1, string.Empty, methodObject
		                                                            ), new Among("kina", -1, 1, string.Empty, methodObject), new Among("ezina", -1, 
		                                                                1, string.Empty, methodObject), new Among("tezina", 23, 1, string.Empty, methodObject
		                                                                    ), new Among("kuna", -1, 1, string.Empty, methodObject), new Among("tuna", -1, 1
		                                                                        , string.Empty, methodObject), new Among("kizuna", -1, 1, string.Empty, methodObject
		                                                                            ), new Among("era", -1, 1, string.Empty, methodObject), new Among("bera", 28, 1, 
		                                                                                string.Empty, methodObject), new Among("arabera", 29, 4, string.Empty, methodObject
		                                                                                    ), new Among("kera", 28, 1, string.Empty, methodObject), new Among("pera", 28, 1
		                                                                                        , string.Empty, methodObject), new Among("orra", -1, 1, string.Empty, methodObject
		                                                                                            ), new Among("korra", 33, 1, string.Empty, methodObject), new Among("dura", -1, 
		                                                                                                1, string.Empty, methodObject), new Among("gura", -1, 1, string.Empty, methodObject
		                                                                                                    ), new Among("kura", -1, 1, string.Empty, methodObject), new Among("tura", -1, 1
		                                                                                                        , string.Empty, methodObject), new Among("eta", -1, 1, string.Empty, methodObject
		                                                                                                            ), new Among("keta", 39, 1, string.Empty, methodObject), new Among("gailua", -1, 
		                                                                                                                1, string.Empty, methodObject), new Among("eza", -1, 1, string.Empty, methodObject
		                                                                                                                    ), new Among("erreza", 42, 1, string.Empty, methodObject), new Among("tza", -1, 
		                                                                                                                        2, string.Empty, methodObject), new Among("gaitza", 44, 1, string.Empty, methodObject
		                                                                                                                            ), new Among("kaitza", 44, 1, string.Empty, methodObject), new Among("kuntza", 44
		                                                                                                                                , 1, string.Empty, methodObject), new Among("ide", -1, 1, string.Empty, methodObject
		                                                                                                                                    ), new Among("bide", 48, 1, string.Empty, methodObject), new Among("kide", 48, 1
		                                                                                                                                        , string.Empty, methodObject), new Among("pide", 48, 1, string.Empty, methodObject
		                                                                                                                                            ), new Among("kunde", -1, 1, string.Empty, methodObject), new Among("tzake", -1, 
		                                                                                                                                                1, string.Empty, methodObject), new Among("tzeke", -1, 1, string.Empty, methodObject
		                                                                                                                                                    ), new Among("le", -1, 1, string.Empty, methodObject), new Among("gale", 55, 1, 
		                                                                                                                                                        string.Empty, methodObject), new Among("taile", 55, 1, string.Empty, methodObject
		                                                                                                                                                            ), new Among("tzaile", 55, 1, string.Empty, methodObject), new Among("gune", -1, 
		                                                                                                                                                                1, string.Empty, methodObject), new Among("kune", -1, 1, string.Empty, methodObject
		                                                                                                                                                                    ), new Among("tze", -1, 1, string.Empty, methodObject), new Among("atze", 61, 1, 
		                                                                                                                                                                        string.Empty, methodObject), new Among("gai", -1, 1, string.Empty, methodObject)
		    , new Among("aldi", -1, 1, string.Empty, methodObject), new Among("taldi", 64, 1
		        , string.Empty, methodObject), new Among("ki", -1, 1, string.Empty, methodObject
		            ), new Among("ari", -1, 1, string.Empty, methodObject), new Among("kari", 67, 1, 
		                string.Empty, methodObject), new Among("lari", 67, 1, string.Empty, methodObject
		                    ), new Among("tari", 67, 1, string.Empty, methodObject), new Among("etari", 70, 
		                        1, string.Empty, methodObject), new Among("garri", -1, 2, string.Empty, methodObject
		                            ), new Among("karri", -1, 1, string.Empty, methodObject), new Among("arazi", -1, 
		                                1, string.Empty, methodObject), new Among("tarazi", 74, 1, string.Empty, methodObject
		                                    ), new Among("an", -1, 1, string.Empty, methodObject), new Among("ean", 76, 1, string.Empty
		                                        , methodObject), new Among("rean", 77, 1, string.Empty, methodObject), new Among
		                                            ("kan", 76, 1, string.Empty, methodObject), new Among("etan", 76, 1, string.Empty
		                                                , methodObject), new Among("atseden", -1, 3, string.Empty, methodObject), new Among
		                                                    ("men", -1, 1, string.Empty, methodObject), new Among("pen", -1, 1, string.Empty
		                                                        , methodObject), new Among("kin", -1, 1, string.Empty, methodObject), new Among(
		                                                            "rekin", 84, 1, string.Empty, methodObject), new Among("ezin", -1, 1, string.Empty
		                                                                , methodObject), new Among("tezin", 86, 1, string.Empty, methodObject), new Among
		                                                                    ("tun", -1, 1, string.Empty, methodObject), new Among("kizun", -1, 1, string.Empty
		                                                                        , methodObject), new Among("go", -1, 1, string.Empty, methodObject), new Among("ago"
		                                                                            , 90, 1, string.Empty, methodObject), new Among("tio", -1, 1, string.Empty, methodObject
		                                                                                ), new Among("dako", -1, 1, string.Empty, methodObject), new Among("or", -1, 1, 
		                                                                                    string.Empty, methodObject), new Among("kor", 94, 1, string.Empty, methodObject)
		    , new Among("tzat", -1, 1, string.Empty, methodObject), new Among("du", -1, 1, string.Empty
		        , methodObject), new Among("gailu", -1, 1, string.Empty, methodObject), new Among
		            ("tu", -1, 1, string.Empty, methodObject), new Among("atu", 99, 1, string.Empty, 
		                methodObject), new Among("aldatu", 100, 1, string.Empty, methodObject), new Among
		                    ("tatu", 100, 1, string.Empty, methodObject), new Among("baditu", 99, 5, string.Empty
		                        , methodObject), new Among("ez", -1, 1, string.Empty, methodObject), new Among("errez"
		                            , 104, 1, string.Empty, methodObject), new Among("tzez", 104, 1, string.Empty, methodObject
		                                ), new Among("gaitz", -1, 1, string.Empty, methodObject), new Among("kaitz", -1, 
		                                    1, string.Empty, methodObject) };

		private static readonly Among[] a_1 = new Among[] { new Among("ada", -1, 1, string.Empty
			, methodObject), new Among("kada", 0, 1, string.Empty, methodObject), new Among(
			"anda", -1, 1, string.Empty, methodObject), new Among("denda", -1, 1, string.Empty
			, methodObject), new Among("gabea", -1, 1, string.Empty, methodObject), new Among
			("kabea", -1, 1, string.Empty, methodObject), new Among("aldea", -1, 1, string.Empty
			, methodObject), new Among("kaldea", 6, 1, string.Empty, methodObject), new Among
			("taldea", 6, 1, string.Empty, methodObject), new Among("ordea", -1, 1, string.Empty
			, methodObject), new Among("zalea", -1, 1, string.Empty, methodObject), new Among
			("tzalea", 10, 1, string.Empty, methodObject), new Among("gilea", -1, 1, string.Empty
			, methodObject), new Among("emea", -1, 1, string.Empty, methodObject), new Among
			("kumea", -1, 1, string.Empty, methodObject), new Among("nea", -1, 1, string.Empty
			, methodObject), new Among("enea", 15, 1, string.Empty, methodObject), new Among
			("zionea", 15, 1, string.Empty, methodObject), new Among("unea", 15, 1, string.Empty
			, methodObject), new Among("gunea", 18, 1, string.Empty, methodObject), new Among
			("pea", -1, 1, string.Empty, methodObject), new Among("aurrea", -1, 1, string.Empty
			, methodObject), new Among("tea", -1, 1, string.Empty, methodObject), new Among(
			"kotea", 22, 1, string.Empty, methodObject), new Among("artea", 22, 1, string.Empty
			, methodObject), new Among("ostea", 22, 1, string.Empty, methodObject), new Among
			("etxea", -1, 1, string.Empty, methodObject), new Among("ga", -1, 1, string.Empty
			, methodObject), new Among("anga", 27, 1, string.Empty, methodObject), new Among
			("gaia", -1, 1, string.Empty, methodObject), new Among("aldia", -1, 1, string.Empty
			, methodObject), new Among("taldia", 30, 1, string.Empty, methodObject), new Among
			("handia", -1, 1, string.Empty, methodObject), new Among("mendia", -1, 1, string.Empty
			, methodObject), new Among("geia", -1, 1, string.Empty, methodObject), new Among
			("egia", -1, 1, string.Empty, methodObject), new Among("degia", 35, 1, string.Empty
			, methodObject), new Among("tegia", 35, 1, string.Empty, methodObject), new Among
			("nahia", -1, 1, string.Empty, methodObject), new Among("ohia", -1, 1, string.Empty
			, methodObject), new Among("kia", -1, 1, string.Empty, methodObject), new Among(
			"tokia", 40, 1, string.Empty, methodObject), new Among("oia", -1, 1, string.Empty
			, methodObject), new Among("koia", 42, 1, string.Empty, methodObject), new Among
			("aria", -1, 1, string.Empty, methodObject), new Among("karia", 44, 1, string.Empty
			, methodObject), new Among("laria", 44, 1, string.Empty, methodObject), new Among
			("taria", 44, 1, string.Empty, methodObject), new Among("eria", -1, 1, string.Empty
			, methodObject), new Among("keria", 48, 1, string.Empty, methodObject), new Among
			("teria", 48, 1, string.Empty, methodObject), new Among("garria", -1, 2, string.Empty
			, methodObject), new Among("larria", -1, 1, string.Empty, methodObject), new Among
			("kirria", -1, 1, string.Empty, methodObject), new Among("duria", -1, 1, string.Empty
			, methodObject), new Among("asia", -1, 1, string.Empty, methodObject), new Among
			("tia", -1, 1, string.Empty, methodObject), new Among("ezia", -1, 1, string.Empty
			, methodObject), new Among("bizia", -1, 1, string.Empty, methodObject), new Among
			("ontzia", -1, 1, string.Empty, methodObject), new Among("ka", -1, 1, string.Empty
			, methodObject), new Among("joka", 60, 3, string.Empty, methodObject), new Among
			("aurka", 60, 10, string.Empty, methodObject), new Among("ska", 60, 1, string.Empty
			, methodObject), new Among("xka", 60, 1, string.Empty, methodObject), new Among(
			"zka", 60, 1, string.Empty, methodObject), new Among("gibela", -1, 1, string.Empty
			, methodObject), new Among("gela", -1, 1, string.Empty, methodObject), new Among
			("kaila", -1, 1, string.Empty, methodObject), new Among("skila", -1, 1, string.Empty
			, methodObject), new Among("tila", -1, 1, string.Empty, methodObject), new Among
			("ola", -1, 1, string.Empty, methodObject), new Among("na", -1, 1, string.Empty, 
			methodObject), new Among("kana", 72, 1, string.Empty, methodObject), new Among("ena"
			, 72, 1, string.Empty, methodObject), new Among("garrena", 74, 1, string.Empty, 
			methodObject), new Among("gerrena", 74, 1, string.Empty, methodObject), new Among
			("urrena", 74, 1, string.Empty, methodObject), new Among("zaina", 72, 1, string.Empty
			, methodObject), new Among("tzaina", 78, 1, string.Empty, methodObject), new Among
			("kina", 72, 1, string.Empty, methodObject), new Among("mina", 72, 1, string.Empty
			, methodObject), new Among("garna", 72, 1, string.Empty, methodObject), new Among
			("una", 72, 1, string.Empty, methodObject), new Among("duna", 83, 1, string.Empty
			, methodObject), new Among("asuna", 83, 1, string.Empty, methodObject), new Among
			("tasuna", 85, 1, string.Empty, methodObject), new Among("ondoa", -1, 1, string.Empty
			, methodObject), new Among("kondoa", 87, 1, string.Empty, methodObject), new Among
			("ngoa", -1, 1, string.Empty, methodObject), new Among("zioa", -1, 1, string.Empty
			, methodObject), new Among("koa", -1, 1, string.Empty, methodObject), new Among(
			"takoa", 91, 1, string.Empty, methodObject), new Among("zkoa", 91, 1, string.Empty
			, methodObject), new Among("noa", -1, 1, string.Empty, methodObject), new Among(
			"zinoa", 94, 1, string.Empty, methodObject), new Among("aroa", -1, 1, string.Empty
			, methodObject), new Among("taroa", 96, 1, string.Empty, methodObject), new Among
			("zaroa", 96, 1, string.Empty, methodObject), new Among("eroa", -1, 1, string.Empty
			, methodObject), new Among("oroa", -1, 1, string.Empty, methodObject), new Among
			("osoa", -1, 1, string.Empty, methodObject), new Among("toa", -1, 1, string.Empty
			, methodObject), new Among("ttoa", 102, 1, string.Empty, methodObject), new Among
			("ztoa", 102, 1, string.Empty, methodObject), new Among("txoa", -1, 1, string.Empty
			, methodObject), new Among("tzoa", -1, 1, string.Empty, methodObject), new Among
			("\u00F1oa", -1, 1, string.Empty, methodObject), new Among("ra", -1, 1, string.Empty
			, methodObject), new Among("ara", 108, 1, string.Empty, methodObject), new Among
			("dara", 109, 1, string.Empty, methodObject), new Among("liara", 109, 1, string.Empty
			, methodObject), new Among("tiara", 109, 1, string.Empty, methodObject), new Among
			("tara", 109, 1, string.Empty, methodObject), new Among("etara", 113, 1, string.Empty
			, methodObject), new Among("tzara", 109, 1, string.Empty, methodObject), new Among
			("bera", 108, 1, string.Empty, methodObject), new Among("kera", 108, 1, string.Empty
			, methodObject), new Among("pera", 108, 1, string.Empty, methodObject), new Among
			("ora", 108, 2, string.Empty, methodObject), new Among("tzarra", 108, 1, string.Empty
			, methodObject), new Among("korra", 108, 1, string.Empty, methodObject), new Among
			("tra", 108, 1, string.Empty, methodObject), new Among("sa", -1, 1, string.Empty
			, methodObject), new Among("osa", 123, 1, string.Empty, methodObject), new Among
			("ta", -1, 1, string.Empty, methodObject), new Among("eta", 125, 1, string.Empty
			, methodObject), new Among("keta", 126, 1, string.Empty, methodObject), new Among
			("sta", 125, 1, string.Empty, methodObject), new Among("dua", -1, 1, string.Empty
			, methodObject), new Among("mendua", 129, 1, string.Empty, methodObject), new Among
			("ordua", 129, 1, string.Empty, methodObject), new Among("lekua", -1, 1, string.Empty
			, methodObject), new Among("burua", -1, 1, string.Empty, methodObject), new Among
			("durua", -1, 1, string.Empty, methodObject), new Among("tsua", -1, 1, string.Empty
			, methodObject), new Among("tua", -1, 1, string.Empty, methodObject), new Among(
			"mentua", 136, 1, string.Empty, methodObject), new Among("estua", 136, 1, string.Empty
			, methodObject), new Among("txua", -1, 1, string.Empty, methodObject), new Among
			("zua", -1, 1, string.Empty, methodObject), new Among("tzua", 140, 1, string.Empty
			, methodObject), new Among("za", -1, 1, string.Empty, methodObject), new Among("eza"
			, 142, 1, string.Empty, methodObject), new Among("eroza", 142, 1, string.Empty, 
			methodObject), new Among("tza", 142, 2, string.Empty, methodObject), new Among("koitza"
			, 145, 1, string.Empty, methodObject), new Among("antza", 145, 1, string.Empty, 
			methodObject), new Among("gintza", 145, 1, string.Empty, methodObject), new Among
			("kintza", 145, 1, string.Empty, methodObject), new Among("kuntza", 145, 1, string.Empty
			, methodObject), new Among("gabe", -1, 1, string.Empty, methodObject), new Among
			("kabe", -1, 1, string.Empty, methodObject), new Among("kide", -1, 1, string.Empty
			, methodObject), new Among("alde", -1, 1, string.Empty, methodObject), new Among
			("kalde", 154, 1, string.Empty, methodObject), new Among("talde", 154, 1, string.Empty
			, methodObject), new Among("orde", -1, 1, string.Empty, methodObject), new Among
			("ge", -1, 1, string.Empty, methodObject), new Among("zale", -1, 1, string.Empty
			, methodObject), new Among("tzale", 159, 1, string.Empty, methodObject), new Among
			("gile", -1, 1, string.Empty, methodObject), new Among("eme", -1, 1, string.Empty
			, methodObject), new Among("kume", -1, 1, string.Empty, methodObject), new Among
			("ne", -1, 1, string.Empty, methodObject), new Among("zione", 164, 1, string.Empty
			, methodObject), new Among("une", 164, 1, string.Empty, methodObject), new Among
			("gune", 166, 1, string.Empty, methodObject), new Among("pe", -1, 1, string.Empty
			, methodObject), new Among("aurre", -1, 1, string.Empty, methodObject), new Among
			("te", -1, 1, string.Empty, methodObject), new Among("kote", 170, 1, string.Empty
			, methodObject), new Among("arte", 170, 1, string.Empty, methodObject), new Among
			("oste", 170, 1, string.Empty, methodObject), new Among("etxe", -1, 1, string.Empty
			, methodObject), new Among("gai", -1, 1, string.Empty, methodObject), new Among(
			"di", -1, 1, string.Empty, methodObject), new Among("aldi", 176, 1, string.Empty
			, methodObject), new Among("taldi", 177, 1, string.Empty, methodObject), new Among
			("geldi", 176, 8, string.Empty, methodObject), new Among("handi", 176, 1, string.Empty
			, methodObject), new Among("mendi", 176, 1, string.Empty, methodObject), new Among
			("gei", -1, 1, string.Empty, methodObject), new Among("egi", -1, 1, string.Empty
			, methodObject), new Among("degi", 183, 1, string.Empty, methodObject), new Among
			("tegi", 183, 1, string.Empty, methodObject), new Among("nahi", -1, 1, string.Empty
			, methodObject), new Among("ohi", -1, 1, string.Empty, methodObject), new Among(
			"ki", -1, 1, string.Empty, methodObject), new Among("toki", 188, 1, string.Empty
			, methodObject), new Among("oi", -1, 1, string.Empty, methodObject), new Among("goi"
			, 190, 1, string.Empty, methodObject), new Among("koi", 190, 1, string.Empty, methodObject
			), new Among("ari", -1, 1, string.Empty, methodObject), new Among("kari", 193, 1
			, string.Empty, methodObject), new Among("lari", 193, 1, string.Empty, methodObject
			), new Among("tari", 193, 1, string.Empty, methodObject), new Among("garri", -1, 
			2, string.Empty, methodObject), new Among("larri", -1, 1, string.Empty, methodObject
			), new Among("kirri", -1, 1, string.Empty, methodObject), new Among("duri", -1, 
			1, string.Empty, methodObject), new Among("asi", -1, 1, string.Empty, methodObject
			), new Among("ti", -1, 1, string.Empty, methodObject), new Among("ontzi", -1, 1, 
			string.Empty, methodObject), new Among("\u00F1i", -1, 1, string.Empty, methodObject
			), new Among("ak", -1, 1, string.Empty, methodObject), new Among("ek", -1, 1, string.Empty
			, methodObject), new Among("tarik", -1, 1, string.Empty, methodObject), new Among
			("gibel", -1, 1, string.Empty, methodObject), new Among("ail", -1, 1, string.Empty
			, methodObject), new Among("kail", 209, 1, string.Empty, methodObject), new Among
			("kan", -1, 1, string.Empty, methodObject), new Among("tan", -1, 1, string.Empty
			, methodObject), new Among("etan", 212, 1, string.Empty, methodObject), new Among
			("en", -1, 4, string.Empty, methodObject), new Among("ren", 214, 2, string.Empty
			, methodObject), new Among("garren", 215, 1, string.Empty, methodObject), new Among
			("gerren", 215, 1, string.Empty, methodObject), new Among("urren", 215, 1, string.Empty
			, methodObject), new Among("ten", 214, 4, string.Empty, methodObject), new Among
			("tzen", 214, 4, string.Empty, methodObject), new Among("zain", -1, 1, string.Empty
			, methodObject), new Among("tzain", 221, 1, string.Empty, methodObject), new Among
			("kin", -1, 1, string.Empty, methodObject), new Among("min", -1, 1, string.Empty
			, methodObject), new Among("dun", -1, 1, string.Empty, methodObject), new Among(
			"asun", -1, 1, string.Empty, methodObject), new Among("tasun", 226, 1, string.Empty
			, methodObject), new Among("aizun", -1, 1, string.Empty, methodObject), new Among
			("ondo", -1, 1, string.Empty, methodObject), new Among("kondo", 229, 1, string.Empty
			, methodObject), new Among("go", -1, 1, string.Empty, methodObject), new Among("ngo"
			, 231, 1, string.Empty, methodObject), new Among("zio", -1, 1, string.Empty, methodObject
			), new Among("ko", -1, 1, string.Empty, methodObject), new Among("trako", 234, 5
			, string.Empty, methodObject), new Among("tako", 234, 1, string.Empty, methodObject
			), new Among("etako", 236, 1, string.Empty, methodObject), new Among("eko", 234, 
			1, string.Empty, methodObject), new Among("tariko", 234, 1, string.Empty, methodObject
			), new Among("sko", 234, 1, string.Empty, methodObject), new Among("tuko", 234, 
			1, string.Empty, methodObject), new Among("minutuko", 241, 6, string.Empty, methodObject
			), new Among("zko", 234, 1, string.Empty, methodObject), new Among("no", -1, 1, 
			string.Empty, methodObject), new Among("zino", 244, 1, string.Empty, methodObject
			), new Among("ro", -1, 1, string.Empty, methodObject), new Among("aro", 246, 1, 
			string.Empty, methodObject), new Among("igaro", 247, 9, string.Empty, methodObject
			), new Among("taro", 247, 1, string.Empty, methodObject), new Among("zaro", 247, 
			1, string.Empty, methodObject), new Among("ero", 246, 1, string.Empty, methodObject
			), new Among("giro", 246, 1, string.Empty, methodObject), new Among("oro", 246, 
			1, string.Empty, methodObject), new Among("oso", -1, 1, string.Empty, methodObject
			), new Among("to", -1, 1, string.Empty, methodObject), new Among("tto", 255, 1, 
			string.Empty, methodObject), new Among("zto", 255, 1, string.Empty, methodObject
			), new Among("txo", -1, 1, string.Empty, methodObject), new Among("tzo", -1, 1, 
			string.Empty, methodObject), new Among("gintzo", 259, 1, string.Empty, methodObject
			), new Among("\u00F1o", -1, 1, string.Empty, methodObject), new Among("zp", -1, 
			1, string.Empty, methodObject), new Among("ar", -1, 1, string.Empty, methodObject
			), new Among("dar", 263, 1, string.Empty, methodObject), new Among("behar", 263, 
			1, string.Empty, methodObject), new Among("zehar", 263, 7, string.Empty, methodObject
			), new Among("liar", 263, 1, string.Empty, methodObject), new Among("tiar", 263, 
			1, string.Empty, methodObject), new Among("tar", 263, 1, string.Empty, methodObject
			), new Among("tzar", 263, 1, string.Empty, methodObject), new Among("or", -1, 2, 
			string.Empty, methodObject), new Among("kor", 271, 1, string.Empty, methodObject
			), new Among("os", -1, 1, string.Empty, methodObject), new Among("ket", -1, 1, string.Empty
			, methodObject), new Among("du", -1, 1, string.Empty, methodObject), new Among("mendu"
			, 275, 1, string.Empty, methodObject), new Among("ordu", 275, 1, string.Empty, methodObject
			), new Among("leku", -1, 1, string.Empty, methodObject), new Among("buru", -1, 2
			, string.Empty, methodObject), new Among("duru", -1, 1, string.Empty, methodObject
			), new Among("tsu", -1, 1, string.Empty, methodObject), new Among("tu", -1, 1, string.Empty
			, methodObject), new Among("tatu", 282, 4, string.Empty, methodObject), new Among
			("mentu", 282, 1, string.Empty, methodObject), new Among("estu", 282, 1, string.Empty
			, methodObject), new Among("txu", -1, 1, string.Empty, methodObject), new Among(
			"zu", -1, 1, string.Empty, methodObject), new Among("tzu", 287, 1, string.Empty, 
			methodObject), new Among("gintzu", 288, 1, string.Empty, methodObject), new Among
			("z", -1, 1, string.Empty, methodObject), new Among("ez", 290, 1, string.Empty, 
			methodObject), new Among("eroz", 290, 1, string.Empty, methodObject), new Among(
			"tz", 290, 1, string.Empty, methodObject), new Among("koitz", 293, 1, string.Empty
			, methodObject) };

		private static readonly Among[] a_2 = new Among[] { new Among("zlea", -1, 2, string.Empty
			, methodObject), new Among("keria", -1, 1, string.Empty, methodObject), new Among
			("la", -1, 1, string.Empty, methodObject), new Among("era", -1, 1, string.Empty, 
			methodObject), new Among("dade", -1, 1, string.Empty, methodObject), new Among("tade"
			, -1, 1, string.Empty, methodObject), new Among("date", -1, 1, string.Empty, methodObject
			), new Among("tate", -1, 1, string.Empty, methodObject), new Among("gi", -1, 1, 
			string.Empty, methodObject), new Among("ki", -1, 1, string.Empty, methodObject), 
			new Among("ik", -1, 1, string.Empty, methodObject), new Among("lanik", 10, 1, string.Empty
			, methodObject), new Among("rik", 10, 1, string.Empty, methodObject), new Among(
			"larik", 12, 1, string.Empty, methodObject), new Among("ztik", 10, 1, string.Empty
			, methodObject), new Among("go", -1, 1, string.Empty, methodObject), new Among("ro"
			, -1, 1, string.Empty, methodObject), new Among("ero", 16, 1, string.Empty, methodObject
			), new Among("to", -1, 1, string.Empty, methodObject) };

		private static readonly int[] g_v = { 17, 65, 16 };

		private int I_p2;

		private int I_p1;

		private int I_pV;

		// This file was generated automatically by the Snowball to Java compiler
		private void Copy_from(BasqueStemmer other)
		{
			I_p2 = other.I_p2;
			I_p1 = other.I_p1;
			I_pV = other.I_pV;
			base.copy_from(other);
		}

		private bool R_mark_regions()
		{
			int v_1;
			int v_2;
			int v_3;
			int v_6;
			int v_8;
			// (, line 25
			I_pV = limit;
			I_p1 = limit;
			I_p2 = limit;
			// do, line 31
			v_1 = cursor;
			do
			{
				do
				{
					// (, line 31
					// or, line 33
					v_2 = cursor;
					do
					{
						// (, line 32
						if (!(in_grouping(g_v, 97, 117)))
						{
							goto lab2_break;
						}
						do
						{
							// or, line 32
							v_3 = cursor;
							do
							{
								// (, line 32
								if (!(out_grouping(g_v, 97, 117)))
								{
									goto lab4_break;
								}
								// gopast, line 32
								while (true)
								{
									do
									{
										if (!(in_grouping(g_v, 97, 117)))
										{
											goto lab6_break;
										}
										goto golab5_break;
lab6_continue: ;
									}
									while (false);
lab6_break: ;
									if (cursor >= limit)
									{
										goto lab4_break;
									}
									cursor++;
golab5_continue: ;
								}
golab5_break: ;
								goto lab3_break;
lab4_continue: ;
							}
							while (false);
lab4_break: ;
							cursor = v_3;
							// (, line 32
							if (!(in_grouping(g_v, 97, 117)))
							{
								goto lab2_break;
							}
							// gopast, line 32
							while (true)
							{
								do
								{
									if (!(out_grouping(g_v, 97, 117)))
									{
										goto lab8_break;
									}
									goto golab7_break;
lab8_continue: ;
								}
								while (false);
lab8_break: ;
								if (cursor >= limit)
								{
									goto lab2_break;
								}
								cursor++;
golab7_continue: ;
							}
golab7_break: ;
lab3_continue: ;
						}
						while (false);
lab3_break: ;
						goto lab1_break;
lab2_continue: ;
					}
					while (false);
lab2_break: ;
					cursor = v_2;
					// (, line 34
					if (!(out_grouping(g_v, 97, 117)))
					{
						goto lab0_break;
					}
					do
					{
						// or, line 34
						v_6 = cursor;
						do
						{
							// (, line 34
							if (!(out_grouping(g_v, 97, 117)))
							{
								goto lab10_break;
							}
							// gopast, line 34
							while (true)
							{
								do
								{
									if (!(in_grouping(g_v, 97, 117)))
									{
										goto lab12_break;
									}
									goto golab11_break;
lab12_continue: ;
								}
								while (false);
lab12_break: ;
								if (cursor >= limit)
								{
									goto lab10_break;
								}
								cursor++;
golab11_continue: ;
							}
golab11_break: ;
							goto lab9_break;
lab10_continue: ;
						}
						while (false);
lab10_break: ;
						cursor = v_6;
						// (, line 34
						if (!(in_grouping(g_v, 97, 117)))
						{
							goto lab0_break;
						}
						// next, line 34
						if (cursor >= limit)
						{
							goto lab0_break;
						}
						cursor++;
lab9_continue: ;
					}
					while (false);
lab9_break: ;
lab1_continue: ;
				}
				while (false);
lab1_break: ;
				// setmark pV, line 35
				I_pV = cursor;
lab0_continue: ;
			}
			while (false);
lab0_break: ;
			cursor = v_1;
			// do, line 37
			v_8 = cursor;
			do
			{
				// (, line 37
				// gopast, line 38
				while (true)
				{
					do
					{
						if (!(in_grouping(g_v, 97, 117)))
						{
							goto lab15_break;
						}
						goto golab14_break;
lab15_continue: ;
					}
					while (false);
lab15_break: ;
					if (cursor >= limit)
					{
						goto lab13_break;
					}
					cursor++;
golab14_continue: ;
				}
golab14_break: ;
				// gopast, line 38
				while (true)
				{
					do
					{
						if (!(out_grouping(g_v, 97, 117)))
						{
							goto lab17_break;
						}
						goto golab16_break;
lab17_continue: ;
					}
					while (false);
lab17_break: ;
					if (cursor >= limit)
					{
						goto lab13_break;
					}
					cursor++;
golab16_continue: ;
				}
golab16_break: ;
				// setmark p1, line 38
				I_p1 = cursor;
				// gopast, line 39
				while (true)
				{
					do
					{
						if (!(in_grouping(g_v, 97, 117)))
						{
							goto lab19_break;
						}
						goto golab18_break;
lab19_continue: ;
					}
					while (false);
lab19_break: ;
					if (cursor >= limit)
					{
						goto lab13_break;
					}
					cursor++;
golab18_continue: ;
				}
golab18_break: ;
				// gopast, line 39
				while (true)
				{
					do
					{
						if (!(out_grouping(g_v, 97, 117)))
						{
							goto lab21_break;
						}
						goto golab20_break;
lab21_continue: ;
					}
					while (false);
lab21_break: ;
					if (cursor >= limit)
					{
						goto lab13_break;
					}
					cursor++;
golab20_continue: ;
				}
golab20_break: ;
				// setmark p2, line 39
				I_p2 = cursor;
lab13_continue: ;
			}
			while (false);
lab13_break: ;
			cursor = v_8;
			return true;
		}

		private bool R_RV()
		{
			if (!(I_pV <= cursor))
			{
				return false;
			}
			return true;
		}

		private bool R_R2()
		{
			if (!(I_p2 <= cursor))
			{
				return false;
			}
			return true;
		}

		private bool R_R1()
		{
			if (!(I_p1 <= cursor))
			{
				return false;
			}
			return true;
		}

		private bool R_aditzak()
		{
			int among_var;
			// (, line 49
			// [, line 50
			ket = cursor;
			// substring, line 50
			among_var = find_among_b(a_0, 109);
			if (among_var == 0)
			{
				return false;
			}
			// ], line 50
			bra = cursor;
			switch (among_var)
			{
				case 0:
				{
					return false;
				}

				case 1:
				{
					// (, line 61
					// call RV, line 61
					if (!R_RV())
					{
						return false;
					}
					// delete, line 61
					slice_del();
					break;
				}

				case 2:
				{
					// (, line 63
					// call R2, line 63
					if (!R_R2())
					{
						return false;
					}
					// delete, line 63
					slice_del();
					break;
				}

				case 3:
				{
					// (, line 65
					// <-, line 65
					slice_from("atseden");
					break;
				}

				case 4:
				{
					// (, line 67
					// <-, line 67
					slice_from("arabera");
					break;
				}

				case 5:
				{
					// (, line 69
					// <-, line 69
					slice_from("baditu");
					break;
				}
			}
			return true;
		}

		private bool R_izenak()
		{
			int among_var;
			// (, line 74
			// [, line 75
			ket = cursor;
			// substring, line 75
			among_var = find_among_b(a_1, 295);
			if (among_var == 0)
			{
				return false;
			}
			// ], line 75
			bra = cursor;
			switch (among_var)
			{
				case 0:
				{
					return false;
				}

				case 1:
				{
					// (, line 105
					// call RV, line 105
					if (!R_RV())
					{
						return false;
					}
					// delete, line 105
					slice_del();
					break;
				}

				case 2:
				{
					// (, line 107
					// call R2, line 107
					if (!R_R2())
					{
						return false;
					}
					// delete, line 107
					slice_del();
					break;
				}

				case 3:
				{
					// (, line 109
					// <-, line 109
					slice_from("jok");
					break;
				}

				case 4:
				{
					// (, line 111
					// call R1, line 111
					if (!R_R1())
					{
						return false;
					}
					// delete, line 111
					slice_del();
					break;
				}

				case 5:
				{
					// (, line 113
					// <-, line 113
					slice_from("tra");
					break;
				}

				case 6:
				{
					// (, line 115
					// <-, line 115
					slice_from("minutu");
					break;
				}

				case 7:
				{
					// (, line 117
					// <-, line 117
					slice_from("zehar");
					break;
				}

				case 8:
				{
					// (, line 119
					// <-, line 119
					slice_from("geldi");
					break;
				}

				case 9:
				{
					// (, line 121
					// <-, line 121
					slice_from("igaro");
					break;
				}

				case 10:
				{
					// (, line 123
					// <-, line 123
					slice_from("aurka");
					break;
				}
			}
			return true;
		}

		private bool R_adjetiboak()
		{
			int among_var;
			// (, line 127
			// [, line 128
			ket = cursor;
			// substring, line 128
			among_var = find_among_b(a_2, 19);
			if (among_var == 0)
			{
				return false;
			}
			// ], line 128
			bra = cursor;
			switch (among_var)
			{
				case 0:
				{
					return false;
				}

				case 1:
				{
					// (, line 131
					// call RV, line 131
					if (!R_RV())
					{
						return false;
					}
					// delete, line 131
					slice_del();
					break;
				}

				case 2:
				{
					// (, line 133
					// <-, line 133
					slice_from("z");
					break;
				}
			}
			return true;
		}

		public override bool Stem()
		{
			int v_1;
			int v_2;
			int v_3;
			int v_4;
			// (, line 139
			// do, line 140
			v_1 = cursor;
			do
			{
				// call mark_regions, line 140
				if (!R_mark_regions())
				{
					goto lab0_break;
				}
lab0_continue: ;
			}
			while (false);
lab0_break: ;
			cursor = v_1;
			// backwards, line 141
			limit_backward = cursor;
			cursor = limit;
			// (, line 141
			// repeat, line 142
			while (true)
			{
				v_2 = limit - cursor;
				do
				{
					// call aditzak, line 142
					if (!R_aditzak())
					{
						goto lab2_break;
					}
					goto replab1_continue;
lab2_continue: ;
				}
				while (false);
lab2_break: ;
				cursor = limit - v_2;
				goto replab1_break;
replab1_continue: ;
			}
replab1_break: ;
			// repeat, line 143
			while (true)
			{
				v_3 = limit - cursor;
				do
				{
					// call izenak, line 143
					if (!R_izenak())
					{
						goto lab4_break;
					}
					goto replab3_continue;
lab4_continue: ;
				}
				while (false);
lab4_break: ;
				cursor = limit - v_3;
				goto replab3_break;
replab3_continue: ;
			}
replab3_break: ;
			// do, line 144
			v_4 = limit - cursor;
			do
			{
				// call adjetiboak, line 144
				if (!R_adjetiboak())
				{
					goto lab5_break;
				}
lab5_continue: ;
			}
			while (false);
lab5_break: ;
			cursor = limit - v_4;
			cursor = limit_backward;
			return true;
		}

		public override bool Equals(object o)
		{
			return o is BasqueStemmer;
		}

		public override int GetHashCode()
		{
			return typeof(BasqueStemmer).FullName.GetHashCode();
		}
	}
}
